name: Build & Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: terafin/mqtt-rules
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: curl
      uses: wei/curl@v1
      with:
        args: -H "X-Docker-Token:${{ secrets.DOCKER_AUTH_TOKEN }}"  -X GET "${{ secrets.WEBHOOK_URL }}?DOCKER_SERVICE_NAME=automation_${{ secrets.CI_PROJECT_NAME }}&DOCKER_IMAGE_PREFIX=${{ secrets.DOCKER_REGISTRY_USER }}&DOCKER_IMAGE_NAME=${{ secrets.CI_PROJECT_NAME }}&DOCKER_IMAGE_TAG=${{ secrets.DOCKER_IMAGE_TAG }}"